/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "worldedit-sui-parent"
include(":we-compat:we-compat-common")
include(":we-compat:we6-compat")
include(":we-compat:we7-compat")
include(":worldedit-sui")
