name: WorldEditSUI
version: ${project.version}
main: eu.kennytv.worldeditsui.WorldEditSUIPlugin
authors: [kennytv]
depend: [WorldEdit]
softdepend: [WorldGuard]
website: https://www.spigotmc.org/resources/worldeditsui.60726/
api-version: 1.13
folia-supported: true

commands:
  worldeditsui:
    description: WorldEditSUI main command.
    aliases: [wesui]
    permission: wesui.command