name: WorldEditSUI
version: "${version}"
main: eu.kennytv.worldeditsui.WorldEditSUIPlugin
authors: [kennytv]
depend: [WorldEdit]
softdepend: [WorldGuard]
website: https://www.spigotmc.org/resources/worldeditsui.60726/
api-version: 1.13

commands:
  worldeditsui:
    description: WorldEditSUI main command.
    aliases: [wesui]
    permission: wesui.command